---
title: "Generating Paper Figures for Parameter Sensitivity"
author: "LylaAtta"
date: "11/19/2020"
output: html_document
---

Setup:   
```{r setup, include=FALSE}
#using velocyto2 evironment 
knitr::opts_chunk$set(echo = FALSE)
library(Rcpp)
library(igraph)
library(matie)
library(RANN)
library(velocyto.R)
library(MUDAN)
library(RSpectra)
library(umap)
library(Rtsne)
library(destiny)
library(ggplot2)
library(patchwork)
library(viridis)
library(svglite)
source("./../projectedNeighbors_weightedCD.R")
```

```{r plotting theme 2}

figtheme = theme_bw(base_size = 18) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        plot.title = element_text(hjust=0.5, size = 24),
        axis.line=element_blank(),axis.text.x=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),axis.title.y=element_blank(),
        legend.position = 'none')

```


### Cycling trajectory  

```{r cycle current}
## make circle like cell cycle
par(mfrow=c(1,1))
x <- matrix(rnorm(1000),nc=2)
y <- x/sqrt(rowSums(x^2))
z = rnorm(500)

## add some jitter
obs <- t(y)
traj = obs
obs <- jitter(obs, amount = 0.25)
## order points counterclockwise
angle <- atan2(obs[2,], obs[1,])
#angle

obs <- obs[, order(angle)]
traj = traj[,order(angle)]
obs = rbind(obs,z)
#obs
## rainbow
col = colorRampPalette(c(rainbow(10)))(ncol(obs))
labels <- paste0('cell', 1:ncol(obs))
## plot
par(mfrow = c(1,2))
plot(t(traj),col = col,pch = 16)
plot(t(obs)[,1:2],col=col, pch=16)
#text(t(obs[,seq(175,225,5)])[,1:2], labels[seq(175,225,5)])

colnames(obs) <- labels
colnames(traj) = labels
names(col) = labels

#plot(t(traj),col = col,pch = 16)
```

Remove some transient cells

```{r jeantestremove}
cells.keep <- setdiff(labels, paste0('cell', 200:300))
# cells.keep

labels <- labels[which(labels %in% cells.keep)]
obs <- obs[,cells.keep]
traj = traj[,cells.keep]
col = col[cells.keep]

#plot
par(mfrow = c(1,2))
plot(t(traj),col = col,pch = 16)
plot(t(obs),col=col, pch=16)
# text(t(obs[,seq(150,199,by=5)]), labels[seq(150,199,by=5)])
# text(t(obs[,seq(200,250,by=7)]), as.character(seq(200,250,by=7))) #labels[seq(200,250,by=7)]
nCells = ncol(traj)
```

Simulate lower dimensional representation of future transcriptional state
```{r cycle projected}
## rotate circle slightly
f = pi*0.1 # adjust as needed
exp = t(obs)[,1:2]
exp[,1] = obs[1,]*cos(f) - obs[2,]*sin(f)
exp[,2] = obs[2,]*cos(f) + obs[1,]*sin(f)
exp = t(exp)
zexp = rnorm(nCells)
exp = rbind(exp,zexp)

plot(t(obs),col=col, pch=16)
points(t(exp)[,1:2],col=col)
arrows(t(obs)[,1],t(obs)[,2],t(exp)[,1],t(exp)[,2])

colnames(exp) <- labels
```

```{r cycle veloviz varying ks}
# fig.width=6, fig.height=7

ks = c(10,30,50,100)
k.embs = list()

par(mfrow = c(2,2))
for (k in ks){
  set.seed(1) 
  g = graphViz(observed = obs, projected = exp,
           k = k, distance_metric = "L2", similarity_metric = "cosine", 
           distance_weight = 1, distance_threshold = 1, similarity_threshold = 0, 
           weighted = TRUE, remove_unconnected = TRUE,
           cell.colors = col, title = "veloviz embedding", 
           plot = FALSE, return_graph = TRUE)
  emb.veloviz = g$fdg_coords
  plot(emb.veloviz, col=col, pch=16, main = paste("K = ",k))
  k.embs[[as.character(k)]] = emb.veloviz
}


#make ggplot
kplots = list()
plot.cols = unique(col)

for (k in c(1:4)){
  emb = k.embs[[k]]
  
  #convert embedding to data frame for plotting 
  emb = as.data.frame(emb)
  emb = cbind(emb, col)
  colnames(emb) = c("X","Y","Cell Type")
  
  #make plot
  p = ggplot(emb, aes(x = X, y = Y, color = `Cell Type`)) +
    geom_point(size = 1) + 
    scale_color_manual(values = plot.cols) +
    #xlab("PC 1") + ylab("PC 2") + 
    ggtitle(paste("k = ",ks[k])) +
    figtheme
  
  kplots[[k]] = p
  #p
  
}


layout = c(
  area(t = 1, l = 1, b = 2, r = 2),
  area(t = 1, l = 3, b = 2, r = 4),
  area(t = 1, l = 5, b = 2, r = 6),
  area(t = 1, l = 7, b = 2, r = 8)
)

p = kplots[[1]] + kplots[[2]] + kplots[[3]] + kplots[[4]] +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(face = "bold", size = 24))

p

```

```{r cycle veloviz varying distance weights}
# fig.width=6, fig.height=7

ws = c(0,0.1,1,10)
w.embs = list()

par(mfrow = c(2,2))
for (w in ws){
  set.seed(1) 
  g = graphViz(observed = obs, projected = exp,
           k = 30, distance_metric = "L2", similarity_metric = "cosine", 
           distance_weight = w, distance_threshold = 1, similarity_threshold = 0, 
           weighted = TRUE, remove_unconnected = TRUE,
           cell.colors = col, title = "veloviz embedding", 
           plot = FALSE, return_graph = TRUE)
  emb.veloviz = g$fdg_coords
  plot(emb.veloviz, col=col, pch=16, main = paste("W = ",w))
  w.embs[[as.character(w)]] = emb.veloviz
}


#make ggplot
wplots = list()
plot.cols = unique(col)

for (w in c(1:4)){
  emb = w.embs[[w]]
  
  #convert embedding to data frame for plotting 
  emb = as.data.frame(emb)
  emb = cbind(emb, col)
  colnames(emb) = c("X","Y","Cell Type")
  
  #make plot
  p = ggplot(emb, aes(x = X, y = Y, color = `Cell Type`)) +
    geom_point(size = 1) + 
    scale_color_manual(values = plot.cols) +
    #xlab("PC 1") + ylab("PC 2") + 
    ggtitle(paste("w = ",ws[w])) +
    figtheme
  
  wplots[[w]] = p
  #p
  
}


layout = c(
  area(t = 1, l = 1, b = 2, r = 2),
  area(t = 1, l = 3, b = 2, r = 4),
  area(t = 1, l = 5, b = 2, r = 6),
  area(t = 1, l = 7, b = 2, r = 8)
)

p = wplots[[1]] + wplots[[2]] + wplots[[3]] + wplots[[4]] +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(face = "bold", size = 24))

p





```

```{r cycle veloviz varying distance threshold}
# fig.width=6, fig.height=7

ds = c(1,0.6,0.4,0.2) #percentile threshold
d.embs = list()

par(mfrow = c(2,2))
for (d in ds){
  set.seed(1) 
  g = graphViz(observed = obs, projected = exp,
           k = 30, distance_metric = "L2", similarity_metric = "cosine", 
           distance_weight = 1, distance_threshold = d, similarity_threshold = 0, 
           weighted = TRUE, remove_unconnected = TRUE,
           cell.colors = col, title = "veloviz embedding", 
           plot = FALSE, return_graph = TRUE)
  emb.veloviz = g$fdg_coords
  plot(emb.veloviz, col=col, pch=16, main = paste("D = ",d))
  d.embs[[as.character(d)]] = emb.veloviz
}

#make ggplot
dplots = list()
plot.cols = unique(col)

for (d in c(1:4)){
  emb = d.embs[[d]]
  
  #convert embedding to data frame for plotting 
  emb = as.data.frame(emb)
  emb = cbind(emb, col)
  colnames(emb) = c("X","Y","Cell Type")
  
  #make plot
  p = ggplot(emb, aes(x = X, y = Y, color = `Cell Type`)) +
    geom_point(size = 1) + 
    scale_color_manual(values = plot.cols) +
    #xlab("PC 1") + ylab("PC 2") + 
    ggtitle(paste("d = ",ds[d])) +
    figtheme
  
  dplots[[d]] = p
  #p
  
}


layout = c(
  area(t = 1, l = 1, b = 2, r = 2),
  area(t = 1, l = 3, b = 2, r = 4),
  area(t = 1, l = 5, b = 2, r = 6),
  area(t = 1, l = 7, b = 2, r = 8)
)

p = dplots[[1]] + dplots[[2]] + dplots[[3]] + dplots[[4]] +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(face = "bold", size = 24))

p





```

```{r cycle veloviz varying similarity threshold}
# fig.width=6, fig.height=7

ts = c(-1,0,0.5,0.7) #percentile threshold
t.embs = list()

par(mfrow = c(2,2))
for (t in ts){
  set.seed(1) 
  g = graphViz(observed = obs, projected = exp,
           k = 30, distance_metric = "L2", similarity_metric = "cosine", 
           distance_weight = 1, distance_threshold = 1, similarity_threshold = t, 
           weighted = TRUE, remove_unconnected = TRUE,
           cell.colors = col, title = "veloviz embedding", 
           plot = FALSE, return_graph = TRUE)
  emb.veloviz = g$fdg_coords
  plot(emb.veloviz, col=col, pch=16, main = paste("T = ",t))
  t.embs[[as.character(t)]] = emb.veloviz
}

#make ggplot
tplots = list()
plot.cols = unique(col)

for (t in c(1:4)){
  emb = t.embs[[t]]
  
  #convert embedding to data frame for plotting 
  emb = as.data.frame(emb)
  emb = cbind(emb, col)
  colnames(emb) = c("X","Y","Cell Type")
  
  #make plot
  p = ggplot(emb, aes(x = X, y = Y, color = `Cell Type`)) +
    geom_point(size = 1) + 
    scale_color_manual(values = plot.cols) +
    #xlab("PC 1") + ylab("PC 2") + 
    ggtitle(paste("t = ",ts[t])) +
    figtheme
  
  tplots[[t]] = p
  #p
  
}


layout = c(
  area(t = 1, l = 1, b = 2, r = 2),
  area(t = 1, l = 3, b = 2, r = 4),
  area(t = 1, l = 5, b = 2, r = 6),
  area(t = 1, l = 7, b = 2, r = 8)
)

p = tplots[[1]] + tplots[[2]] + tplots[[3]] + tplots[[4]] +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(face = "bold", size = 24))

p

```
### Plotting Combined 

```{r}
layout = c(
  area(t = 1, l = 1, b = 2, r = 2),
  area(t = 1, l = 3, b = 2, r = 4),
  area(t = 1, l = 5, b = 2, r = 6),
  area(t = 1, l = 7, b = 2, r = 8),
  
  area(t = 3, l = 1, b = 4, r = 2),
  area(t = 3, l = 3, b = 4, r = 4),
  area(t = 3, l = 5, b = 4, r = 6),
  area(t = 3, l = 7, b = 4, r = 8),
  
  area(t = 5, l = 1, b = 6, r = 2),
  area(t = 5, l = 3, b = 6, r = 4),
  area(t = 5, l = 5, b = 6, r = 6),
  area(t = 5, l = 7, b = 6, r = 8),
  
  area(t = 7, l = 1, b = 8, r = 2),
  area(t = 7, l = 3, b = 8, r = 4),
  area(t = 7, l = 5, b = 8, r = 6),
  area(t = 7, l = 7, b = 8, r = 8)
  
)

p = kplots[[1]] + kplots[[2]] + kplots[[3]] + kplots[[4]] +
  wplots[[1]] + wplots[[2]] + wplots[[3]] + wplots[[4]] +
  dplots[[1]] + dplots[[2]] + dplots[[3]] + dplots[[4]] +
  tplots[[1]] + tplots[[2]] + tplots[[3]] + tplots[[4]] +
  plot_layout(design = layout) +
  plot_annotation(tag_levels = "A") & theme(plot.tag = element_text(face = "bold", size = 24))

ggsave(file = "figsup_cycle_params.svg", plot = p, width = 12, height = 12)
ggsave(file = "figsup_cycle_params.png", plot = p, width = 12, height = 12)

```







