---
title: "MERFISH example"
author: "Jean Fan"
date: "11/17/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = 'hide')
library(veloviz)
```

## MERFISH
[add description of data]  

Load preprocessed data  
```{r load data}
col = MERFISH$col
pcs = MERFISH$pcs
vel = MERFISH$vel
```

Load cell cycle genes - keep merfish genes that are cell cycle genes  
```{r}
cycle.genes = read.csv("/Users/lylaatta/Desktop/geneset_278.csv",header = FALSE)
# cycle.genes = cycle.genes$Gene
cycle.genes = cycle.genes$V1

curr = vel$current
proj = vel$projected

merfish.genes = rownames(curr)
merfish.cycle.genes = merfish.genes[which(merfish.genes %in% cycle.genes)]

curr.cycle = curr[merfish.cycle.genes,]
proj.cycle = proj[merfish.cycle.genes,]

```

Build VeloViz graph on all genes  
```{r veloviz}
# , fig.height = 11, fig.width = 7
curr = vel$current
proj = vel$projected

veloviz = buildVeloviz(
  curr = curr, 
  proj = proj,
  normalize.depth = TRUE, 
  use.ods.genes = FALSE,
  pca = TRUE,
  nPCs = 5,
  center = TRUE,
  scale = TRUE, 
  k = 5,
  similarity.threshold = 0,
  distance.weight = 0.01,
  distance.threshold = 0.9,
  weighted = TRUE,
  seed = 0,
  verbose = FALSE
)

# par(mfrow=c(3,2))
emb.veloviz = veloviz$fdg_coords
plotEmbedding(emb.veloviz, groups=col[rownames(emb.veloviz)], main='veloviz')
# g = plotVeloviz(veloviz, clusters=col[rownames(emb.veloviz)], seed=0, verbose=TRUE)
sapply(c('MCM6', 'CDC6', 'KIF2C', 'CCNF'), function(g) {
  gexp <- scale(curr[g,])[,1]
  plotEmbedding(emb.veloviz, col=gexp, main=g)
})
```

Compare to other embeddings  
```{r, fig.height = 11, fig.width = 7}

#PCA
layout(matrix(c(1,1,2,3,4,5), 3, 2, byrow = TRUE))
emb.pcs = pcs[,1:2]
plotEmbedding(emb.pcs, col=col, main='PCA')
sapply(c('MCM6', 'CDC6', 'KIF2C', 'CCNF'), function(g) {
  gexp <- scale(curr[g,])[,1]
  plotEmbedding(emb.pcs, col=gexp, main=g)
})

#tSNE 
set.seed(1)
layout(matrix(c(1,1,2,3,4,5), 3, 2, byrow = TRUE))
emb.tsne = Rtsne::Rtsne(pcs[,1:5], perplexity = 100)$Y
rownames(emb.tsne) = rownames(pcs)
plotEmbedding(emb.tsne, col=col, main='tSNE', 
              xlab = "t-SNE X", ylab = "t-SNE Y")
sapply(c('MCM6', 'CDC6', 'KIF2C', 'CCNF'), function(g) {
  gexp <- scale(curr[g,])[,1]
  plotEmbedding(emb.tsne, col=gexp, main=g)
})

#UMAP
set.seed(1)
layout(matrix(c(1,1,2,3,4,5), 3, 2, byrow = TRUE))
emb.umap = umap::umap(pcs[,1:5], min_dist = 0.3)$layout
rownames(emb.umap) = rownames(pcs)
plotEmbedding(emb.umap, col=col, main='UMAP',
              xlab = "UMAP X", ylab = "UMAP Y")
sapply(c('MCM6', 'CDC6', 'KIF2C', 'CCNF'), function(g) {
  gexp <- scale(curr[g,])[,1]
  plotEmbedding(emb.umap, col=gexp, main=g)
})

#veloviz
layout(matrix(c(1,1,2,3,4,5), 3, 2, byrow = TRUE))
plotEmbedding(emb.veloviz, groups=col[rownames(emb.veloviz)], main='veloviz')
sapply(c('MCM6', 'CDC6', 'KIF2C', 'CCNF'), function(g) {
  gexp <- scale(curr[g,])[,1]
  plotEmbedding(emb.veloviz, col=gexp, main=g)
})

```















```{r merfish_init, eval=FALSE, include = FALSE}
dir <- 'path/to/downloaded/data'
cell_gexp <- as.matrix(read.csv(paste0(dir, 'S12_cell_gexp.csv.gz'), 
                                row.names=1))
print(cell_gexp[1:5,1:5])
nuc_gexp <- as.matrix(read.csv(paste0(dir, 'S14_nuc_gexp.csv.gz'), 
                               row.names=1))
print(nuc_gexp[1:5,1:5])
cyto_gexp <- cell_gexp - nuc_gexp

gene_info <- read.csv(paste0(dir, 'S1_codebook.csv.gz'), 
                      header=FALSE, stringsAsFactors = FALSE)
long.genes <- gene_info[2:9051,1]
short.genes <- gene_info[9280:10279,1]
bad.genes <- gene_info[,1][grepl('Blank', gene_info[,1])]

## use subset of genes
test.genes <- long.genes
cell_gexp <- cell_gexp[test.genes,]
nuc_gexp <- nuc_gexp[test.genes,]
cyto_gexp <- cyto_gexp[test.genes,]
cd <- cell_gexp

## annotate batch
batch <- sapply(colnames(cd), function(x) strsplit(x, '_')[[1]][1])
batch <- factor(batch)
table(batch)

## limit to one batch in example
subcells <- names(batch)[batch=='B1']
spliced = cyto_gexp[, subcells]
unspliced = nuc_gexp[, subcells]
vi <- rowSums(spliced) > 10 & rowSums(unspliced) > 10
spliced = spliced[vi,]
unspliced = unspliced[vi,]

library(veloviz)
## normalize
counts = spliced + unspliced # use cell count
cpm = normalizeDepth(counts) # cpm normalize
matnorm = normalizeVariance(cpm)
matnorm = log10(matnorm+1)
pcs <- reduceDimensions(matnorm, center = TRUE, scale = TRUE, nPCs = 50)

## use first 2 PCs as embedding
emb <- pcs[,1:2]
rownames(emb) <- colnames(all.cpm)

## use angle as color
angle <- atan2(emb[,2], emb[,1])
obs <- emb[order(angle), ]
col = colorRampPalette(c(rainbow(10)))(nrow(obs))
names(col) = rownames(obs)
## double check
plotEmbedding(emb, col=col[rownames(emb)])
sapply(c('MCM6', 'CCNF'), function(g) {
  plotEmbedding(emb, col=scale(matnorm[g,], main=g)
})

## velocity model
library(velocyto.R)
cell.dist = as.dist(1-cor(t(pcs))) # cell distance in PC space
vel = gene.relative.velocity.estimates(spliced,
                                       unspliced,
                                       kCells=30,
                                       cell.dist=cell.dist,
                                       fit.quantile=0.1)

## save
MERFISH <- list(
  nuc = Matrix::Matrix(unspliced, sparse=TRUE),
  cyto = Matrix::Matrix(spliced, sparse=TRUE),
  col = col,
  pcs = pcs,
  cell.dist = cell.dist,
  vel = vel
)
usethis::use_data(MERFISH, overwrite = TRUE)
```

```{r merfish_main_pca, eval=FALSE, include = FALSE}
library(veloviz)
data(MERFISH)

par(mfrow=c(2,2), mar=rep(1,4))
## 2D embedding by PCA
emb.pcs = MERFISH$pcs[,1:2]
plotEmbedding(emb.pcs, col=MERFISH$col, main='PCA')
emb.pcs = MERFISH$pcs[,2:3]
plotEmbedding(emb.pcs, col=MERFISH$col, main='PCA')
emb.pcs = MERFISH$pcs[,3:4]
plotEmbedding(emb.pcs, col=MERFISH$col, main='PCA')
emb.pcs = MERFISH$pcs[,4:5]
plotEmbedding(emb.pcs, col=MERFISH$col, main='PCA')
```

```{r merfish_main_tsne, eval=FALSE, include = FALSE}
par(mfrow=c(2,2), mar=rep(1,4))
## 2D embedding by tSNE
set.seed(0)
emb.tsne = Rtsne::Rtsne(MERFISH$pcs[,1:5], perplexity = 10)$Y
rownames(emb.tsne) <- rownames(MERFISH$pcs)
plotEmbedding(emb.tsne, col=MERFISH$col, main='tSNE')
set.seed(0)
emb.tsne = Rtsne::Rtsne(MERFISH$pcs[,1:5], perplexity = 30)$Y
rownames(emb.tsne) <- rownames(MERFISH$pcs)
plotEmbedding(emb.tsne, col=MERFISH$col, main='tSNE')
set.seed(0)
emb.tsne = Rtsne::Rtsne(MERFISH$pcs[,1:5], perplexity = 50)$Y
rownames(emb.tsne) <- rownames(MERFISH$pcs)
plotEmbedding(emb.tsne, col=MERFISH$col, main='tSNE')
set.seed(0)
emb.tsne = Rtsne::Rtsne(MERFISH$pcs[,1:5], perplexity = 100)$Y
rownames(emb.tsne) <- rownames(MERFISH$pcs)
plotEmbedding(emb.tsne, col=MERFISH$col, main='tSNE')
```

```{r merfish_main_umap, eval=FALSE, include = FALSE}
par(mfrow=c(2,2), mar=rep(1,4))
## 2D embedding by UMAP
set.seed(0)
emb.umap = uwot::umap(MERFISH$pcs[,1:5], min_dist = 0.1)
rownames(emb.umap) <- rownames(MERFISH$pcs)
plotEmbedding(emb.umap, col=MERFISH$col, main='UMAP')
set.seed(0)
emb.umap = uwot::umap(MERFISH$pcs[,1:5], min_dist = 0.3)
rownames(emb.umap) <- rownames(MERFISH$pcs)
plotEmbedding(emb.umap, col=MERFISH$col, main='UMAP')
set.seed(0)
emb.umap = uwot::umap(MERFISH$pcs[,1:5], min_dist = 0.5)
rownames(emb.umap) <- rownames(MERFISH$pcs)
plotEmbedding(emb.umap, col=MERFISH$col, main='UMAP')
set.seed(0)
emb.umap = uwot::umap(MERFISH$pcs[,1:5], min_dist = 1)
rownames(emb.umap) <- rownames(MERFISH$pcs)
plotEmbedding(emb.umap, col=MERFISH$col, main='UMAP')
```

```{r merfish_main_veloviz, eval=FALSE, include = FALSE}
par(mfrow=c(2,2), mar=rep(1,4))
## 2D embedding by veloviz
g <- buildVeloviz(MERFISH$vel$current, 
                  MERFISH$vel$projected,
                  k = 10, 
                  nPCs = 5,
                  center=TRUE, scale=FALSE, 
                  use.ods.genes = TRUE, 
                  max.ods.genes = 1000,
                  alpha = 0.05,
                  verbose = FALSE)
plotEmbedding(g$fdg_coords, col = MERFISH$col[rownames(g$fdg_coords)], main='veloviz')
g <- buildVeloviz(MERFISH$vel$current, 
                  MERFISH$vel$projected,
                  k = 30, 
                  nPCs = 5,
                  center=TRUE, scale=FALSE, 
                  use.ods.genes = TRUE, 
                  max.ods.genes = 1000,
                  alpha = 0.05,
                  verbose = FALSE)
plotEmbedding(g$fdg_coords, col = MERFISH$col[rownames(g$fdg_coords)], main='veloviz')
g <- buildVeloviz(MERFISH$vel$current, 
                  MERFISH$vel$projected,
                  k = 50, 
                  nPCs = 5,
                  center=TRUE, scale=FALSE, 
                  use.ods.genes = TRUE, 
                  max.ods.genes = 1000,
                  alpha = 0.05,
                  verbose = FALSE)
plotEmbedding(g$fdg_coords, col = MERFISH$col[rownames(g$fdg_coords)], main='veloviz')
g <- buildVeloviz(MERFISH$vel$current, 
                  MERFISH$vel$projected,
                  k = 100, 
                  nPCs = 5,
                  center=TRUE, scale=FALSE, 
                  use.ods.genes = TRUE, 
                  max.ods.genes = 1000,
                  alpha = 0.05,
                  verbose = FALSE)
plotEmbedding(g$fdg_coords, col = MERFISH$col[rownames(g$fdg_coords)], main='veloviz')

```

```{r merfish_optional, eval=FALSE, include = FALSE}
library(velocyto.R)
show.velocity.on.embedding.cor(scale(emb.pcs), vel, 
                               n = 100, show.grid.flow = TRUE, grid.n = 20,
                               cell.colors = col, arrow.scale = 1)
show.velocity.on.embedding.cor(scale(emb.tsne), vel, 
                               n = 100, show.grid.flow = TRUE, grid.n = 20,
                               cell.colors = col, arrow.scale = 1)
show.velocity.on.embedding.cor(scale(emb.umap), vel, 
                               n = 100, show.grid.flow = TRUE, grid.n = 20,
                               cell.colors = col, arrow.scale = 1)
show.velocity.on.embedding.cor(scale(g$fdg_coords), vel, 
                               n = 100, show.grid.flow = TRUE, grid.n = 20,
                               cell.colors = col, arrow.scale = 1)
```


#####

Build VeloViz graph on cell cycle genes  
```{r}
veloviz.cycle = buildVeloviz(
  curr = curr.cycle, 
  proj = proj.cycle,
  normalize.depth = TRUE, 
  use.ods.genes = FALSE,
  pca = TRUE,
  nPCs = 4,
  center = TRUE,
  scale = TRUE, 
  k = 100,
  similarity.threshold = 0.25,
  distance.weight = 0.5,
  distance.threshold = 1,
  weighted = TRUE,
  seed = 0,
  verbose = FALSE
)
par(mfrow = c(1,2))
emb.veloviz.cycle = veloviz.cycle$fdg_coords
plotEmbedding(emb.veloviz.cycle, groups=col[rownames(emb.veloviz.cycle)], main='veloviz')
g = plotVeloviz(veloviz.cycle, clusters=col[rownames(emb.veloviz.cycle)], seed=0, verbose=TRUE)

sapply(c('MCM6', 'CDC6', 'KIF2C', 'CCNF'), function(g) {
  gexp <- scale(curr[g,])[,1]
  plotEmbedding(emb.veloviz.cycle, col=gexp, main=g)
})

```







