theme: jekyll-theme-minimal
description: Creating RNA-velocity informed 2D embeddings for single cell transcriptomics
logo: https://github.com/JEFworks-Lab/veloviz/blob/package_extras/docs/img/logo_final.png?raw=true
