# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

myDist <- function(cell_i, proj_i, nn_i, distance_metric, similarity_metric, distance_weight) {
    .Call('_veloviz_myDist', PACKAGE = 'veloviz', cell_i, proj_i, nn_i, distance_metric, similarity_metric, distance_weight)
}

pwiseDists <- function(cell_i, proj_i, obs_exc_i, distance_metric, similarity_metric, distance_weight) {
    .Call('_veloviz_pwiseDists', PACKAGE = 'veloviz', cell_i, proj_i, obs_exc_i, distance_metric, similarity_metric, distance_weight)
}

pwiseCors <- function(deltaExp, neighborIdx, nNeighbors) {
    .Call('_veloviz_pwiseCors', PACKAGE = 'veloviz', deltaExp, neighborIdx, nNeighbors)
}

